name: Dungeons
author: carterz30cal
main: com.carterz30cal.dungeons.Dungeons
version: 0.1.16
api-version: 1.13
depend: [ProtocolLib,Votifier]
commands:
 dungeons:
  description: "all command functionality for dungeons."
  usage: "Usage: /<command> menu"
  aliases: d
 warp:
  description: "warp back to the hub"
  usage: "Incorrect destination!"
  aliases: w
 leaderboard:
  description: "get the top online players"
  usage: ""
  aliases: top
 trade:
  description: "trade"
  usage: "/trade <player>"
  aliases: t
 market:
  description: "open material marketplace"
  usage: "/market"
  aliases: mk
 stats:
  description: "see your stats!"
  usage: "you don't."
 playtime:
  description: "see how long you've played for"
  usage: "this will never appear"
 discord:
  description: "discord link"
  usage: "huh."
 maxitem:
  description: "max held item"
  usage: "This command is admin-only"
 tutorial:
  description: "go through the tutorial again"
  usage: "Players only"
 vote:
  description: "links to voting sites"
 effects:
  description: "See your active effects!"
  aliases: ef
  